### ISSUE TITLE
Missing react skill

### ISSUE THREAD

**Issue by metalvegetarianoprogresivo** [cmedinilla/react-resume#1]
This is a react project and react is not on the skills?

**Comment by cmedinilla** [comment]
it's my first app in React, i can't say i am a react expert yet

**Comment by metalvegetarianoprogresivo** [comment]
yet you have the skill

**Comment by cmedinilla** [comment]
Added react in the resume.json example in commit c61214dc06ee3392467764331254981f3d68cab4
