### ISSUE TITLE
A Getting Started section at the README would help a lot

### ISSUE THREAD

**Issue by binario200** [cmedinilla/react-resume#2]
If I'm new at react or even using node or npm how can I get started? 

a series of step by step would help a lot. 

something like:

https://github.com/binario200/hackathon-starter#getting-started

**Comment by cmedinilla** [comment]
Thanks for the feedback,  i will work on create a How Can I Get Started  section ASAP 
And answering your question
The only pre-requisite is node.js 6.0+ installed 
* Clone the repo
* Run npm install
* Run npm start

**Comment by cmedinilla** [comment]
Added a little Getting Started Section in commit  bd4f7b21cd5d8c2edae0bc3d94dc5e1a5b94553a
